services:
  - type: web
    name: next-frontend
    env: node
    region: oregon
    plan: starter
    buildCommand: 'npm install --force && npm run build'
    startCommand: 'npm start'
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
      - key: NODE_OPTIONS
        value: '--max-old-space-size=4096'
